### ISSUE TITLE
fix not in ansible galaxy

### ISSUE THREAD

**Issue by CrimsonRot** [abalage/ansible_collection_elasticstack_podman#15]
Hi,

I just saw, that the last fix is not downloadable via ansible galaxy, could u start the build/upload?
Sadly I do not know the right process for this. Or could u tell me how I could start it?

https://github.com/abalage/ansible_collection_elasticstack_podman/pull/14

Hope u have a great time.

**Comment by abalage** [comment]
Let me have a look and upload a new release.

**Comment by abalage** [comment]
New release v1.0.4 is out both in GitHub and Ansible Galaxy. 
Thanks for the reminder :)
